// Produces a single self-contained worker file to paste into a dashboard editor, since pasting
// code into a browser has no way to resolve an import of a second file. Generated from the same
// sources the tests run against, so the pasteable copy can never drift from the tested one.
import { readFileSync, writeFileSync } from 'fs';

const merge = readFileSync(new URL('./merge.js', import.meta.url), 'utf8')
  .replace(/^import .*$/gm, '')
  .replace(/^export /gm, '');
const worker = readFileSync(new URL('./worker.js', import.meta.url), 'utf8')
  .replace(/^import \{ merge \} from '\.\/merge\.js';$/m, '');

writeFileSync(new URL('./worker.single.js', import.meta.url),
`// Room Check sync server - ONE FILE, for pasting into the Cloudflare dashboard editor.
// Generated by build-single.mjs from worker.js + merge.js. Edit those, not this.
${merge}
${worker}`);
console.log('wrote worker.single.js');
