// Room Check sync server - ONE FILE, for pasting into the Cloudflare dashboard editor.
// Generated by build-single.mjs from worker.js + merge.js. Edit those, not this.
// The same reconciliation rule as the app's Merge.kt, written once and used by both the sync
// server and the website. Two implementations of a merge rule that disagree are worse than none,
// so the pair is pinned to a shared set of cases in server/fixtures.json.

function markKey(sid, pid) { return "m:" + sid + ":" + pid; }
function tonightKey(pid) { return "t:" + pid; }
function noteKey(pid) { return "n:" + pid; }
const CLOSED_KEY = "c";

function emptyNight() { return { marks: {}, tonight: [], notes: {}, closed: false, ts: {} }; }

/** Every cell either side knows anything about. */
function keysOf(n) {
  const out = new Set();
  for (const sid of Object.keys(n.marks || {}))
    for (const pid of Object.keys(n.marks[sid] || {})) out.add(markKey(sid, pid));
  for (const pid of n.tonight || []) out.add(tonightKey(pid));
  for (const pid of Object.keys(n.notes || {})) out.add(noteKey(pid));
  out.add(CLOSED_KEY);
  for (const k of Object.keys(n.ts || {})) out.add(k);
  return out;
}

/** The cell's value, or null when empty - unmarking is a value too, not an absence of one. */
function valueOf(n, key) {
  if (key === CLOSED_KEY) return n.closed ? "1" : null;
  if (key.startsWith("m:")) {
    const i = key.indexOf(":", 2);
    const sid = key.slice(2, i), pid = key.slice(i + 1);
    return (n.marks && n.marks[sid] && n.marks[sid][pid]) || null;
  }
  if (key.startsWith("t:")) return (n.tonight || []).includes(key.slice(2)) ? "1" : null;
  if (key.startsWith("n:")) return (n.notes || {})[key.slice(2)] ?? null;
  return null;
}

function setValue(n, key, value) {
  if (key === CLOSED_KEY) { n.closed = value !== null; return; }
  if (key.startsWith("m:")) {
    const i = key.indexOf(":", 2);
    const sid = key.slice(2, i), pid = key.slice(i + 1);
    n.marks[sid] = n.marks[sid] || {};
    if (value === null) delete n.marks[sid][pid]; else n.marks[sid][pid] = value;
    return;
  }
  if (key.startsWith("t:")) {
    const pid = key.slice(2);
    const at = n.tonight.indexOf(pid);
    if (value !== null && at < 0) n.tonight.push(pid);
    if (value === null && at >= 0) n.tonight.splice(at, 1);
    return;
  }
  if (key.startsWith("n:")) {
    const pid = key.slice(2);
    if (value === null || value === "") delete n.notes[pid]; else n.notes[pid] = value;
  }
}

/**
 * The later edit of each cell wins. Ties fall back to comparing the values, so merging a pair in
 * either order lands in the same place - without that two devices can swap edits forever.
 */
function merge(local, remote) {
  const out = emptyNight();
  const keys = [...new Set([...keysOf(local || emptyNight()), ...keysOf(remote || emptyNight())])].sort();
  const L = local || emptyNight(), R = remote || emptyNight();
  for (const key of keys) {
    const lt = (L.ts || {})[key] || 0;
    const rt = (R.ts || {})[key] || 0;
    const lv = valueOf(L, key);
    const rv = valueOf(R, key);
    const takeRemote = lt !== rt ? rt > lt : (rv || "") > (lv || "");
    const value = takeRemote ? rv : lv;
    setValue(out, key, value);
    const stamp = Math.max(lt, rt);
    if (stamp > 0 || value !== null) out.ts[key] = stamp;
  }
  // drop slots that ended up with nothing in them, so an empty night stays empty
  for (const sid of Object.keys(out.marks)) if (!Object.keys(out.marks[sid]).length) delete out.marks[sid];
  out.tonight.sort();
  return out;
}

// Room Check sync server - a Cloudflare Worker over a KV namespace.
//
// It holds nights, nothing else: no accounts, no roster, no history beyond what the clients send.
// Both clients stay offline-first and treat their own copy as the truth; this only reconciles.
// Every write is merged into what is already stored using the shared cell-by-cell rule, so two
// people marking at the same moment both keep their marks rather than the later save winning.



const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
};

const json = (body, status = 200) =>
  new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json', ...CORS } });

/** date -> when the server last touched it, so a client can ask only for what it is missing. */
const INDEX = 'idx';

async function readIndex(env) {
  return (await env.NIGHTS.get(INDEX, 'json')) || {};
}

export default {
  async fetch(request, env) {
    if (request.method === 'OPTIONS') return new Response(null, { headers: CORS });

    const token = (request.headers.get('Authorization') || '').replace(/^Bearer\s+/i, '');
    if (!env.SYNC_TOKEN || token !== env.SYNC_TOKEN) return json({ error: 'unauthorized' }, 401);
    if (request.method !== 'POST') return json({ error: 'use POST' }, 405);

    const url = new URL(request.url);
    const body = await request.json().catch(() => ({}));
    const now = Date.now();

    if (url.pathname.endsWith('/pull')) {
      const since = Number(body.since) || 0;
      const idx = await readIndex(env);
      const nights = {};
      // only the nights that changed since this client last asked - a full history every time
      // would grow without bound and be sent over a phone connection at 11pm
      for (const [date, at] of Object.entries(idx)) {
        if (at > since) {
          const n = await env.NIGHTS.get('n:' + date, 'json');
          if (n) nights[date] = n;
        }
      }
      return json({ now, nights });
    }

    if (url.pathname.endsWith('/push')) {
      const incoming = body.nights || {};
      const idx = await readIndex(env);
      const merged = {};
      for (const [date, night] of Object.entries(incoming)) {
        if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) continue;
        const stored = await env.NIGHTS.get('n:' + date, 'json');
        const out = merge(stored, night);
        await env.NIGHTS.put('n:' + date, JSON.stringify(out));
        idx[date] = now;
        merged[date] = out;
      }
      if (Object.keys(merged).length) await env.NIGHTS.put(INDEX, JSON.stringify(idx));
      // handing the merged night straight back saves the client a second round trip to find out
      // what its edit turned into once someone else's was folded in
      return json({ now, nights: merged });
    }

    return json({ error: 'not found' }, 404);
  },
};
